# Logistic regression implementation



In [5]:
import numpy as np
import tensorflow as tf

xy = np.loadtxt('logistic_example_data.txt', unpack=True, dtype='float32')

x_data = xy[0:-1]
y_data = xy[-1]

print(x_data, y_data)

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W = tf.Variable(tf.random_uniform( [1,len(x_data)], -1.0, 1.0))

h = tf.matmul(W,X)
hypothesis = tf.div(1.0,(1.0+ tf.exp(-h)) )

cost = -1.0* tf.reduce_mean( 
    Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis)
)

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()

# Launch the graph
sess = tf.Session()
sess.run(init)

# Fit the line.
for step in range(2001):
    sess.run(train, feed_dict={X:x_data, Y:y_data} )
    if step % 20 == 0:
        print(step, sess.run(cost, feed_dict={X:x_data, Y:y_data}), sess.run(W) )





[[ 1.  1.  1.  1.  1.  1.]
 [ 2.  3.  3.  5.  7.  2.]
 [ 1.  2.  4.  5.  5.  5.]] [ 0.  0.  0.  1.  1.  1.]
0 0.78661 [[ 0.13119489 -0.76045436  0.67581022]]
20 0.619523 [[-0.1178995  -0.47406173  0.69696409]]
40 0.576705 [[-0.37934545 -0.35999528  0.63117409]]
60 0.54264 [[-0.62350494 -0.27458593  0.59559429]]
80 0.51453 [[-0.85177135 -0.21151628  0.58211279]]
100 0.490575 [[-1.06566918 -0.16458736  0.58342111]]
120 0.469706 [[-1.26664674 -0.12882848  0.5939936 ]]
140 0.451272 [[-1.45600665 -0.10067263  0.61005521]]
160 0.434842 [[-1.63489902 -0.0777097   0.62917769]]
180 0.420103 [[-1.80433571 -0.05835951  0.64985818]]
200 0.406809 [[-1.96520591 -0.04159715  0.67119133]]
220 0.394763 [[-2.11829281 -0.02675599  0.6926446 ]]
240 0.383801 [[-2.26428938 -0.01339609  0.71391314]]
260 0.373784 [[ -2.40380907e+00  -1.22103863e-03   7.34828949e-01]]
280 0.364598 [[-2.53739595  0.00997519  0.75530547]]
300 0.356141 [[-2.66553593  0.02034081  0.77530432]]
320 0.348331 [[-2.78866124  0.02998609

In [3]:
# Verify hypothesis
print( sess.run(hypothesis,feed_dict={X:[[1],[2],[2]]})> 0.5 )
print( sess.run(hypothesis,feed_dict={X:[[1],[5],[5]]})> 0.5 )

[[False]]
[[ True]]


In [4]:
print(x_data, y_data)

[[ 1.  1.  1.  1.  1.  1.]
 [ 2.  3.  3.  5.  7.  2.]
 [ 1.  2.  4.  5.  5.  5.]] [ 0.  0.  0.  1.  1.  1.]
