# XOR operation by NeuralNetwork

In [2]:
# Implement code for Sung Kim's TF lecture. See https://www.youtube.com/watch?v=9i7FBbcZPMA&feature=youtu.be

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

# Need to change data structure. THESE LINES ARE DIFFERNT FROM Video BUT IT MAKES THIS CODE WORKS!
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [2,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )




0 0.710807 [[-0.23799537 -0.64334887]
 [ 0.99189657  0.35737014]] [[ 0.00626673]
 [ 0.81748635]]
1000 0.69128 [[-0.3450323  -0.79193425]
 [ 1.05605483  0.44133425]] [[-0.28741881]
 [ 0.76176196]]
2000 0.677758 [[-0.62844026 -1.28290963]
 [ 1.27633893  0.90647316]] [[-0.62846887]
 [ 1.15018058]]
3000 0.453673 [[-2.06531715 -3.04426694]
 [ 2.50935221  2.75427008]] [[-2.33258724]
 [ 3.2621007 ]]
4000 0.135482 [[-4.00421095 -4.55536938]
 [ 4.30133009  4.35006046]] [[-5.21226311]
 [ 5.92975426]]
5000 0.0639115 [[-4.778584   -5.1712079 ]
 [ 5.05409527  4.97500181]] [[-6.70084286]
 [ 7.32425356]]
6000 0.0401752 [[-5.18592644 -5.50901747]
 [ 5.45449162  5.31195784]] [[-7.58791351]
 [ 8.1762228 ]]
7000 0.0289248 [[-5.45069551 -5.73371077]
 [ 5.71594238  5.5343771 ]] [[-8.20870018]
 [ 8.77964783]]
8000 0.022471 [[-5.64311171 -5.89939642]
 [ 5.90645838  5.69770765]] [[-8.68360901]
 [ 9.24435234]]
[array([[ 0.02181667],
       [ 0.98046219],
       [ 0.97081202],
       [ 0.01830276]], dtype=float

# Use 'wide' 10 neurals network to solve XOR problem. 

In [1]:
# Use 'wide' 10 neurals network to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Wide network: Use more neurons in each layer. 
W1 = tf.Variable(tf.random_uniform( [2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [10,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )


0 0.698332 [[ 0.96428281 -0.12110915 -0.31592286  0.76239818 -0.69043756 -0.97537237
   0.55899614  0.18925501 -0.84202445  0.07934161]
 [ 0.24333893  0.01567234 -0.70100856  0.53511059  0.37110645  0.82214242
  -0.02609664 -0.21773313  0.90476358 -0.55190843]] [[-0.85513866]
 [-0.01900747]
 [ 0.96581256]
 [ 0.5512079 ]
 [ 0.04411528]
 [ 0.36710292]
 [-0.82939547]
 [ 0.86053824]
 [-0.50499928]
 [ 0.09310402]]
1000 0.625351 [[ 0.9742502  -0.12143259 -0.00807752  1.74074697 -0.68707424 -1.32227337
   0.61815172  0.21211752 -1.00341845  0.08500257]
 [-0.23306109  0.01406289 -0.57828975  1.66302443  0.37282851  0.83871174
  -0.20501171 -0.20546037  1.52710509 -0.54845244]] [[-0.93262035]
 [-0.13510767]
 [ 0.77094966]
 [ 1.66649032]
 [-0.02218213]
 [ 0.67374319]
 [-0.95231545]
 [ 0.75435144]
 [-1.18097603]
 [-0.02579555]]
2000 0.260651 [[ 1.81638861 -0.05677377 -0.16886614  3.49939966 -0.74043673 -2.69569921
   1.28675354 -0.0903553  -2.55314016  0.06836709]
 [-0.6281994   0.06073546 -0.814

# Use 'Deep' neurals network to solve XOR problem. 

In [4]:
# Use 'Deep' neurals network to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Deep network configuration.: Use more layers. 
W1 = tf.Variable(tf.random_uniform( [2,5], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [5,4], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform( [4,1], -1.0, 1.0))


b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b2 = tf.Variable(tf.zeros([4]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias1")


# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
L3 =  tf.sigmoid(tf.matmul(L2,W2)+b2)
hypothesis = tf.sigmoid( tf.matmul(L3,W3) + b3)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )

0 0.712705 [[-0.59350902 -0.67372859  0.51656502 -0.58937883  0.16740671]
 [ 0.44365084 -0.85480618 -0.56178772  0.39537501  0.00100397]] [[ 0.09966767  0.27328455  0.57515174  0.64497215]
 [-0.36029056 -0.83498359 -0.92396492 -0.90298247]
 [ 0.27738696 -0.63415033  0.58206475  0.45997095]
 [-0.86903203  0.68250346  0.03744411 -0.82934904]
 [-0.71550012 -0.75235897  0.57310534  0.88734448]]
1000 0.692316 [[-0.60306162 -0.71467155  0.52749366 -0.59106761  0.17790778]
 [ 0.44007629 -0.8949843  -0.56116164  0.40749621  0.00812146]] [[ 0.08650257  0.27103561  0.57885695  0.64066291]
 [-0.38364092 -0.86036581 -0.90914267 -0.9202643 ]
 [ 0.27332133 -0.65346545  0.58555984  0.45384622]
 [-0.88189089  0.68000591  0.04122877 -0.83374399]
 [-0.72589868 -0.76709533  0.57675767  0.88153666]]
2000 0.691883 [[-0.61373061 -0.77513069  0.54033595 -0.59614438  0.18840498]
 [ 0.43748003 -0.95310426 -0.56095886  0.4191606   0.01371179]] [[ 0.08156946  0.27835953  0.58021683  0.64135718]
 [-0.40486252 -0.