# XOR operation by NeuralNetwork

In [2]:
# Implement code for Sung Kim's TF lecture. See https://www.youtube.com/watch?v=9i7FBbcZPMA&feature=youtu.be

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

# Need to change data structure. THESE LINES ARE DIFFERNT FROM Video BUT IT MAKES THIS CODE WORKS!
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [2,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )




0 0.694192 [[ 0.38814735 -0.20966713]
 [ 0.1806348  -0.375875  ]] [[-0.44491372]
 [ 0.70176834]]
1000 0.693339 [[ 0.32086322 -0.07168127]
 [ 0.07590109 -0.27049291]] [[-0.41793168]
 [ 0.61851215]]
2000 0.69322 [[ 0.29030085 -0.00923738]
 [ 0.01765184 -0.22450809]] [[-0.40088201]
 [ 0.59317988]]
3000 0.69318 [[ 0.27482644  0.02630654]
 [-0.02019913 -0.19851612]] [[-0.39234942]
 [ 0.58106726]]
4000 0.693162 [[ 0.26721501  0.04954347]
 [-0.04742356 -0.18198174]] [[-0.38752374]
 [ 0.57454139]]
5000 0.693152 [[ 0.26464677  0.06638727]
 [-0.0686458  -0.1711266 ]] [[-0.3846783 ]
 [ 0.57098961]]
6000 0.693143 [[ 0.26596051  0.07975778]
 [-0.08650951 -0.16434366]] [[-0.38314295]
 [ 0.56933081]]
7000 0.693135 [[ 0.27079007  0.09132771]
 [-0.10277356 -0.16093186]] [[-0.38270462]
 [ 0.56909269]]
8000 0.693126 [[ 0.27926892  0.10221041]
 [-0.11880027 -0.16067655]] [[-0.38341314]
 [ 0.57011634]]
[array([[ 0.50291359],
       [ 0.50005174],
       [ 0.49992329],
       [ 0.49700138]], dtype=float32),

# Use 'wide' neural network to solve XOR problem. 

In [3]:
# Use 'wide' neural network (10 neurals) to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Wide network: Use more neurons in each layer. 
W1 = tf.Variable(tf.random_uniform( [2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [10,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )


0 0.733474 [[ 0.70221001 -0.53889644  0.11911839 -0.86905229 -0.93228507 -0.8713544
  -0.54055244  0.57190865 -0.25249514 -0.40831131]
 [-0.5210098   0.75651574  0.43360707  0.75772208  0.61628681 -0.37962148
   0.90395856  0.04139151 -0.48191801 -0.17461844]] [[-0.93642765]
 [ 0.65975887]
 [-0.42310634]
 [ 0.52158654]
 [-0.56722403]
 [-0.73981887]
 [-0.72574544]
 [ 0.79894501]
 [-0.34472358]
 [ 0.29835099]]
1000 0.629403 [[ 1.07106316 -0.85133737  0.05937625 -1.42341197 -0.78972965 -1.63911951
  -0.83708769  0.74785751 -0.34079257 -0.36304   ]
 [-0.50998515  0.55439878  0.46740225  0.79922533  0.95587134 -1.3901459
   1.56642306  0.36407518 -0.50718886 -0.17423981]] [[-0.82659197]
 [ 0.86280787]
 [-0.27249357]
 [ 1.04360044]
 [-0.57415181]
 [-1.43375754]
 [-1.13861907]
 [ 1.08004034]
 [-0.14067982]
 [ 0.52612907]]
2000 0.262367 [[ 1.71268225 -1.69308043  0.06929957 -3.06719041 -1.01242387 -3.18095994
  -2.38301849  1.43026102 -0.34650099 -0.45042449]
 [-0.79469007  0.81020445  0.54038

# Use 'Deep' neural network to solve XOR problem. 

In [6]:
# Use 'Deep' neural network to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Deep network configuration.: Use more layers. 
W1 = tf.Variable(tf.random_uniform( [2,5], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [5,4], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform( [4,1], -1.0, 1.0))


b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b2 = tf.Variable(tf.zeros([4]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias3")


# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
L3 =  tf.sigmoid(tf.matmul(L2,W2)+b2)
hypothesis = tf.sigmoid( tf.matmul(L3,W3) + b3)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(20001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )

0 0.733715 [[-0.90483856  0.39183104 -0.80646926  0.48715159 -0.03867198]
 [-0.98090732  0.39945036  0.73835498  0.63823467  0.64624053]] [[ 0.9423843   0.15881255  0.47409219 -0.28724322]
 [-0.49680737 -0.48129719 -0.0422513  -0.13418159]
 [-0.78293115 -0.89813536  0.78211033 -0.42110744]
 [ 0.35311505 -0.46266755 -0.16855457 -0.78781158]
 [-0.16092953  0.15618949  0.08073769  0.26624981]]
1000 0.692295 [[-0.85716099  0.43061852 -0.9121626   0.53153592 -0.05550944]
 [-0.93971235  0.41017795  0.65681183  0.65434468  0.6495443 ]] [[ 0.9099291   0.35112122  0.32124013 -0.30948704]
 [-0.5027045  -0.48166487 -0.05387558 -0.13512751]
 [-0.79377627 -0.83726209  0.75983828 -0.42540571]
 [ 0.35112628 -0.48936456 -0.15751441 -0.78551543]
 [-0.17277393  0.20559324  0.03444846  0.26044434]]
2000 0.689509 [[-0.94431549  0.49662146 -1.09612274  0.5951156  -0.07635334]
 [-0.99529576  0.43714464  0.69347006  0.68266165  0.65419662]] [[ 0.91793668  0.56196362  0.18147701 -0.33218566]
 [-0.50405532 -0.