# XOR operation by NeuralNetwork

In [2]:
# Implement code for Sung Kim's TF lecture. See https://www.youtube.com/watch?v=9i7FBbcZPMA&feature=youtu.be

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

# Need to change data structure. THESE LINES ARE DIFFERNT FROM Video BUT IT MAKES THIS CODE WORKS!
x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

W1 = tf.Variable(tf.random_uniform( [2,2], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [2,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([2]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )




0 0.694192 [[ 0.38814735 -0.20966713]
 [ 0.1806348  -0.375875  ]] [[-0.44491372]
 [ 0.70176834]]
1000 0.693339 [[ 0.32086322 -0.07168127]
 [ 0.07590109 -0.27049291]] [[-0.41793168]
 [ 0.61851215]]
2000 0.69322 [[ 0.29030085 -0.00923738]
 [ 0.01765184 -0.22450809]] [[-0.40088201]
 [ 0.59317988]]
3000 0.69318 [[ 0.27482644  0.02630654]
 [-0.02019913 -0.19851612]] [[-0.39234942]
 [ 0.58106726]]
4000 0.693162 [[ 0.26721501  0.04954347]
 [-0.04742356 -0.18198174]] [[-0.38752374]
 [ 0.57454139]]
5000 0.693152 [[ 0.26464677  0.06638727]
 [-0.0686458  -0.1711266 ]] [[-0.3846783 ]
 [ 0.57098961]]
6000 0.693143 [[ 0.26596051  0.07975778]
 [-0.08650951 -0.16434366]] [[-0.38314295]
 [ 0.56933081]]
7000 0.693135 [[ 0.27079007  0.09132771]
 [-0.10277356 -0.16093186]] [[-0.38270462]
 [ 0.56909269]]
8000 0.693126 [[ 0.27926892  0.10221041]
 [-0.11880027 -0.16067655]] [[-0.38341314]
 [ 0.57011634]]
[array([[ 0.50291359],
       [ 0.50005174],
       [ 0.49992329],
       [ 0.49700138]], dtype=float32),

# Use 'wide' neural network to solve XOR problem. 

In [3]:
# Use 'wide' neural network (10 neurals) to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Wide network: Use more neurons in each layer. 
W1 = tf.Variable(tf.random_uniform( [2,10], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [10,1], -1.0, 1.0))

b1 = tf.Variable(tf.zeros([10]), name="Bias1")
b2 = tf.Variable(tf.zeros([1]), name="Bias2")

# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
hypothesis = tf.sigmoid( tf.matmul(L2,W2) + b2)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )


0 0.733474 [[ 0.70221001 -0.53889644  0.11911839 -0.86905229 -0.93228507 -0.8713544
  -0.54055244  0.57190865 -0.25249514 -0.40831131]
 [-0.5210098   0.75651574  0.43360707  0.75772208  0.61628681 -0.37962148
   0.90395856  0.04139151 -0.48191801 -0.17461844]] [[-0.93642765]
 [ 0.65975887]
 [-0.42310634]
 [ 0.52158654]
 [-0.56722403]
 [-0.73981887]
 [-0.72574544]
 [ 0.79894501]
 [-0.34472358]
 [ 0.29835099]]
1000 0.629403 [[ 1.07106316 -0.85133737  0.05937625 -1.42341197 -0.78972965 -1.63911951
  -0.83708769  0.74785751 -0.34079257 -0.36304   ]
 [-0.50998515  0.55439878  0.46740225  0.79922533  0.95587134 -1.3901459
   1.56642306  0.36407518 -0.50718886 -0.17423981]] [[-0.82659197]
 [ 0.86280787]
 [-0.27249357]
 [ 1.04360044]
 [-0.57415181]
 [-1.43375754]
 [-1.13861907]
 [ 1.08004034]
 [-0.14067982]
 [ 0.52612907]]
2000 0.262367 [[ 1.71268225 -1.69308043  0.06929957 -3.06719041 -1.01242387 -3.18095994
  -2.38301849  1.43026102 -0.34650099 -0.45042449]
 [-0.79469007  0.81020445  0.54038

# Use 'Deep' neural network to solve XOR problem. 

In [4]:
# Use 'Deep' neural network to solve XOR problem. 

import numpy as np
import tensorflow as tf

xy = np.loadtxt('xor_dataset.txt', unpack=True)

x_data = np.transpose( xy[0:-1] )
y_data = np.reshape( xy[-1], (4,1) )

X = tf.placeholder(tf.float32)
Y = tf.placeholder(tf.float32)

# Deep network configuration.: Use more layers. 
W1 = tf.Variable(tf.random_uniform( [2,5], -1.0, 1.0))
W2 = tf.Variable(tf.random_uniform( [5,4], -1.0, 1.0))
W3 = tf.Variable(tf.random_uniform( [4,1], -1.0, 1.0))


b1 = tf.Variable(tf.zeros([5]), name="Bias1")
b2 = tf.Variable(tf.zeros([4]), name="Bias2")
b3 = tf.Variable(tf.zeros([1]), name="Bias1")


# Hypotheses 
L2 =  tf.sigmoid(tf.matmul(X,W1)+b1)
L3 =  tf.sigmoid(tf.matmul(L2,W2)+b2)
hypothesis = tf.sigmoid( tf.matmul(L3,W3) + b3)

# Cost function 
cost = -tf.reduce_mean( Y*tf.log(hypothesis)+(1-Y)* tf.log(1.-hypothesis) )

# Minimize cost.
a = tf.Variable(0.1)
optimizer = tf.train.GradientDescentOptimizer(a)
train = optimizer.minimize(cost)

# Initializa all variables.
init = tf.initialize_all_variables()


# Launch the graph
with tf.Session() as sess:
    sess.run(init)
    
    for step in range(8001):
        sess.run(train, feed_dict={X:x_data, Y:y_data})
        
        if step % 1000 == 0:
            print(
                step, 
                sess.run(cost, feed_dict={X:x_data, Y:y_data}), 
                sess.run(W1),
                sess.run(W2)
            )
    
    # Test model
    correct_prediction = tf.equal( tf.floor(hypothesis+0.5), Y)
    accuracy = tf.reduce_mean(tf.cast( correct_prediction, "float" ) )
    
    # Check accuracy
    print( sess.run( [hypothesis, tf.floor(hypothesis+0.5), correct_prediction, accuracy], 
                   feed_dict={X:x_data, Y:y_data}) )
    print( "Accuracy:", accuracy.eval({X:x_data, Y:y_data}) )

0 0.721231 [[-0.18185458  0.63436347  0.98922336  0.57007366 -0.03416014]
 [ 0.561068   -0.77762485 -0.84238166 -0.46791831  0.80516267]] [[ 0.1613846  -0.19442379  0.11019868 -0.47708055]
 [ 0.46501455 -0.41790804 -0.67535931  0.21991305]
 [-0.42998701 -0.73683506  0.9118821   0.5156315 ]
 [ 0.58294934 -0.79343522  0.7976166  -0.13877687]
 [-0.27826256 -0.43033704  0.41770962 -0.14359935]]
1000 0.690814 [[ -1.84638709e-01   7.67681837e-01   8.75721753e-01   5.94293296e-01
    3.85065534e-04]
 [  5.74159026e-01  -7.36427665e-01  -1.05523765e+00  -4.59358811e-01
    8.08623910e-01]] [[ 0.18169942 -0.1852659   0.09747643 -0.50821173]
 [ 0.52221298 -0.44674158 -0.74510795  0.19449112]
 [-0.43110609 -0.76135391  0.88575405  0.52451724]
 [ 0.63008791 -0.81463087  0.74210912 -0.16305436]
 [-0.26150265 -0.4186874   0.41168559 -0.1738344 ]]
2000 0.683271 [[-0.1973902   1.02923679  1.02841508  0.61634266  0.05312655]
 [ 0.58164006 -0.79080409 -1.45131207 -0.47987288  0.81781423]] [[ 0.15550624 